name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  pr_commented:
  # This job only runs for pull request comments
    name: PR Comment
    if: contains(github.event.comment.body, '/update-tokens') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../
    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v2
      
      - name: "List current directory"
        run: |
          pwd && ls -a
          git checkout -b chore/update-tokens
          git branch --show-current

      - name: 'Cloning cornershop-customer-app-translation'
        # cornershop-customer-app-translations is created because the cloned repository is the same
        run: |
          mkdir cornershop-customer-app-translations && cd cornershop-customer-app-translations
          git clone https://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@github.com/devjorgecastro/test-github-action.git
          chmod +x ./test-github-action/script.sh
          cd ..
          pwd
          ls -a
      
      - name: 'Updating tokens'
        id: updating_tokens
        run: |
          ./cornershop-customer-app-translations/test-github-action/script.sh
          cd test-github-action
          if [ -n "$(git status --porcelain)" ]; then
            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
          fi

      - name: 'Create Pull Request'
        if: ${{ steps.updating_tokens.outputs.HAS_CHANGES }}
        run: |
          cd test-github-action && pwd && ls -a
          echo "hay cambios pendientes = ${{ steps.updating_tokens.outputs.HAS_CHANGES }}"


