name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  pr_commented:
  # This job only runs for pull request comments
    name: PR Comment
    if: contains(github.event.comment.body, '/update-tokens') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Current branch'
          pwd
          ls -a
          
        env:
          NUMBER: ${{ github.event.issue.number }}
