name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  pr_commented:
  # This job only runs for pull request comments
    name: PR Comment
    if: contains(github.event.comment.body, '/update-tokens') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v2
      
      - name: 'Create file tes'
        run: |
          pwd && ls -a
      #- name: Set up Git
      #  run: git config --global credential.helper store

      #- name: Authenticate with Github
      #  run: echo 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 > ~/.github_token && git config --global credential.helper 'store --file ~/.github_token'

      - name: "Create new branch"
        run: git checkout -b chore/update-tokens

      - name: Initialize bot git config
        run: |
          git config user.name 'Jorge Castro'
          git config user.email 'dev.jorgecastro@gmail.com'
          #git remote set-url origin https://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@github.com/devjorgecastro/test-github-action.git

      - name: 'Cloning cornershop-customer-app-translation'
        # cornershop-customer-app-translations is created because the cloned repository is the same
        working-directory: ../
        run: |
          mkdir cornershop-customer-app-translations && cd cornershop-customer-app-translations
          git clone https://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@github.com/devjorgecastro/test-github-action.git
          chmod +x ./test-github-action/script.sh

      
      - name: 'Updating tokens'
        id: updating_tokens
        working-directory: ../
        run: |
          pwd && ls -a
          ./cornershop-customer-app-translations/test-github-action/script.sh
          cd cornershop-customer-app-translations/test-github-action/
          echo 'Showing remote'
          git remote -v
          cd ../..
          cd test-github-action
          if [ -n "$(git status --porcelain)" ]; then
            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
          fi

      - name: 'Saving changes'
        if: ${{ steps.updating_tokens.outputs.HAS_CHANGES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
          GITHUB_USER: devjorgecastro
        run: |
          #git remote set-url origin https://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:x-oauth-basic@github.com/devjorgecastro/test-github-action.git
          git remote -v
          git add .
          git commit -m 'Tokens were updated'
          echo '<<< Push new Branch >>>'
          git push -u origin chore/update-tokens

      - name: Create Pull Request
        id: create_pull_request
        #if: ${{ steps.updating_tokens.outputs.HAS_CHANGES }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repo/issues/:issue_id/comments
          repo: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
          body: |
            This PR is created for Update tokens
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}