name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  pr_commented:
  # This job only runs for pull request comments
    name: PR Comment
    if: contains(github.event.comment.body, '/update-tokens') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Obtener datos del PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload;
            const baseRef = payload.pull_request.base.ref;
            const headRef = payload.pull_request.head.ref;
            const regex = /^release\/\d+\.\d+\.\d+/;
            if (baseRef === 'devel' && regex.test(headRef)) {
              const ramaCambios = headRef;
              console.log(`La rama de cambios del PR es ${ramaCambios}`);
              // A partir de aquí puedes hacer lo que quieras con el nombre de la rama
            } else {
              console.log('El PR no cumple las condiciones necesarias');
            }