name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  deploy-check:
    runs-on: ubuntu-latest
    steps:
      - name: acknowledge deployment request to commenter
        id: check
        uses: khan/pull-request-comment-trigger@master
        with:
          trigger: "/upadte-tokens"
          reaction: rocket
