name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  pr_commented:
  # This job only runs for pull request comments
    name: PR Comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ..
          mkdir test
          cd test
          git clone https://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@github.com/devjorgecastro/test-github-action.git
          cd ..
          echo Listando directorios
          ls
          echo A Comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
