name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  pr_commented:
  # This job only runs for pull request comments
    name: PR Comment
    if: contains(github.event.comment.body, '/update-tokens') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
    - name: Pull Request Info
      run: |
        # Obtener el número del pull request a partir de la URL
        PR_NUMBER=$(echo "${{ github.event.issue.pull_request.url }}" | sed 's#.*/##')

        # Obtener información del pull request usando la API de GitHub
        PR_INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_ACTION_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER})

        # Extraer la información del pull request
        PR_BASE=$(echo "${PR_INFO}" | jq -r '.base.ref')
        PR_HEAD=$(echo "${PR_INFO}" | jq -r '.head.ref')
        PR_BODY=$(echo "${PR_INFO}" | jq -r '.body')

        # Imprimir la información del pull request
        echo "La rama base del PR es: ${PR_BASE}"
        echo "La rama de cambios del PR es: ${PR_HEAD}"
        echo "El mensaje del PR es: ${PR_BODY}"