name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  check_bash_version:
    name: Check Bash Version
    runs-on: ubuntu-latest
    steps:
    - name: Install bash 3
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        wget http://ftp.gnu.org/gnu/bash/bash-3.2.57.tar.gz
        tar -zxvf bash-3.2.57.tar.gz
        cd bash-3.2.57
        ./configure
        make
        sudo make install
        bash --version

  extract_pr_info:
    name: Pull Request Info
    runs-on: ubuntu-latest
    steps:
    - name: Extract Pull Request Info
      id: extract_pull_request_info
      if: github.event.issue.pull_request
      run: |
        if [ "${{ github.event.comment.body }}" != "/update-tokens"]; then
          echo "The comment is different to '/update-tokens'"
          exit 1
        fi

        # Obtener el número del pull request a partir de la URL
        PR_NUMBER=$(echo "${{ github.event.issue.pull_request.url }}" | sed 's#.*/##')

        # Obtener información del pull request usando la API de GitHub
        PR_INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_ACTION_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER})

        # Extraer la información del pull request
        PR_BASE=$(echo "${PR_INFO}" | jq -r '.base.ref')
        PR_HEAD=$(echo "${PR_INFO}" | jq -r '.head.ref')
        PR_DESCRIPTION=$(echo "${PR_INFO}" | jq -r '.body')

        echo "PR_BASE=${PR_BASE}" >> $GITHUB_ENV
        echo "PR_HEAD=${PR_HEAD}" >> $GITHUB_ENV
        echo "PR_DESCRIPTION=${PR_DESCRIPTION}" >> $GITHUB_ENV
    outputs:
      PR_BASE: ${{ env.PR_BASE }}
      PR_HEAD: ${{ env.PR_HEAD }}
      PR_DESCRIPTION: ${{ env.PR_DESCRIPTION }}
  
  create_pull_request:
  # This job only runs for pull request comments
    name: "Pull Request to update ${{ needs.extract_pr_info.outputs.PR_HEAD }} tokens"
    needs: extract_pr_info
    runs-on: ubuntu-latest
    steps:
      - name: Checking remote branch
        id: checking_remote_branch
        if: github.event.comment.body == '/update-tokens' && github.event.issue.pull_request
        run: |
          if [ "${{ github.event.comment.body }}" != "/update-tokens"]; then
            echo "The comment is different to '/update-tokens'"
            exit 1
          fi

          if ! git ls-remote --heads origin chore/update-tokens | grep -q chore/update-tokens; then
            echo "NEW_BRANCH_EXIST=false" >> $GITHUB_OUTPUT
          else
            echo "NEW_BRANCH_EXIST=true" >> $GITHUB_OUTPUT
          fi

      - name: Update Comment
        if: github.event.comment.body == '/update-tokens' && github.event.issue.pull_request
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GH_ACTION_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |

            Processing... ⏳ 🙇🏽
          reactions: 'eyes'


      - name: "Cloning repository"
        if: ${{ steps.checking_remote_branch.outcome == 'success' }}
        uses: actions/checkout@v3

      - name: "Create new branch"
        run: |
          echo "SHOW INFO = ${{ steps.checking_remote_branch.outcome }}"
          echo "pull request head = ${{ env.PR_HEAD }}"
          git fetch
          git checkout release/1.0.0
          git checkout -b chore/update-tokens

      - name: Initialize bot git config
        if: ${{ steps.checking_remote_branch.outcome == 'success' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          #git remote set-url origin https://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@github.com/devjorgecastro/test-github-action.git

      - name: 'Cloning cornershop-customer-app-translation'
        if: ${{ steps.checking_remote_branch.outcome == 'success' }}
        # cornershop-customer-app-translations is created because the cloned repository is the same
        working-directory: ../
        run: |
          mkdir cornershop-customer-app-translations && cd cornershop-customer-app-translations
          git clone https://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@github.com/devjorgecastro/test-github-action.git
          chmod +x ./test-github-action/script.sh

      
      - name: 'Updating tokens'
        if: ${{ steps.checking_remote_branch.outcome == 'success' }}
        id: updating_tokens
        working-directory: ../
        run: |
          pwd && ls -a
          ./cornershop-customer-app-translations/test-github-action/script.sh
          echo 'Showing remote'
          cd test-github-action
          echo '<<< current branch >>>'
          git branch --show-current
          if [ -n "$(git status --porcelain)" ]; then
            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
          fi

      - name: 'Saving changes'
        id: saving_changes
        if: ${{ steps.updating_tokens.outputs.HAS_CHANGES }}
        run: |
          git add .
          git commit -m 'Tokens were updated'
          echo '<<< Push new Branch >>>'
          git push --set-upstream origin chore/update-tokens
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}

      - name: Create Pull Request
        id: create_pull_request
        if: ${{ steps.updating_tokens.outputs.HAS_CHANGES }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_ACTION_TOKEN }}
          script: |
            const title = 'Update tokens';
            const baseRef = 'release/1.0.0';
            const headRef = 'chore/update-tokens';
            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              base: baseRef,
              head: headRef,
              body: `This pull request updates tokens.`
            });
            console.log(`Created pull request: ${pullRequest.html_url}`);

      - name: Update Comment before pull request was created
        if: github.event.comment.body == '/update-tokens' && github.event.issue.pull_request
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GH_ACTION_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ${{ github.event.comment.body }}

            The pull request to refresh the xxxxx branch tokens has been created successfully.
            Please don't forget to check the upgrade tokens before merging to this release branch.

            - link del Pull request https://github.com/${{ github.repository }}/pull/${{ github.event.issue.number }}
          reactions: 'eyes, rocket'
          edit-mode: replace