name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  pr_commented:
  # This job only runs for pull request comments
    name: PR Comment
    if: contains(github.event.comment.body, '/update-tokens') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v2
      
      - name: "List current directory"
        run: pwd && ls -a

      - name: 'Cloning cornershop-customer-app-translation'
        run: |
          cd .. && pwd && ls -a

     
