name: Update Tokens in Release
on:
  issue_comment:
    type: [created]

jobs:
  pr_commented:
  # This job only runs for pull request comments
    name: PR Comment
    if: contains(github.event.comment.body, '/update-tokens') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: "Cloning repository"
        uses: actions/checkout@v3
      
      #- name: Set up Git
      #  run: git config --global credential.helper store

      #- name: Authenticate with Github
      #  run: echo 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 > ~/.github_token && git config --global credential.helper 'store --file ~/.github_token'

      - name: "Create new branch"
        run: git checkout -b chore/update-tokens

      - name: Initialize bot git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          #git remote set-url origin https://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@github.com/devjorgecastro/test-github-action.git

      - name: 'Cloning cornershop-customer-app-translation'
        # cornershop-customer-app-translations is created because the cloned repository is the same
        working-directory: ../
        run: |
          mkdir cornershop-customer-app-translations && cd cornershop-customer-app-translations
          git clone https://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@github.com/devjorgecastro/test-github-action.git
          chmod +x ./test-github-action/script.sh

      
      - name: 'Updating tokens'
        id: updating_tokens
        working-directory: ../
        run: |
          pwd && ls -a
          ./cornershop-customer-app-translations/test-github-action/script.sh
          echo 'Showing remote'
          cd test-github-action
          echo '<<< current branch >>>'
          git branch --show-current
          if [ -n "$(git status --porcelain)" ]; then
            echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_CHANGES=false" >> $GITHUB_OUTPUT
          fi

      - name: 'Saving changes'
        if: ${{ steps.updating_tokens.outputs.HAS_CHANGES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
        run: |
          git branch --show-current
          pwd && ls -a
          #git remote set-url origin https://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@github.com/devjorgecastro/test-github-action.git
          #git remote set-url origin https://x-access-token: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@github.com/devjorgecastro/test-github-action.git
          git remote -v
          git add .
          git commit -m 'Tokens were updated'
          git log -1
          echo '<<< Push new Branch >>>'
          git push --set-upstream origin chore/update-tokens
          echo '<<< git pull >>>'
          git log -1
          git pull
          git push

      - name: Create Pull Request
        id: create_pull_request
        if: ${{ steps.updating_tokens.outputs.HAS_CHANGES }}
        uses: peter-evans/create-pull-request@v4
        with:
          base: release/1.0.0
          branch: chore/update-tokens
          title: Titulo de Prueba
          body: |
            Esta es una descripcion de prueba de varias lineas
            Esta es la segunda linea en la descripcion.
            Este es otro parrafo en la tercera linea de la descripcion del PR
          token: ${{ secrets.GH_ACTION_TOKEN }}