name: Test Action
on:
  push:
    branches:
     - '^release\/\d+\.\d+\.\d+$'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run My Action
        run: echo "Test Success!"
