name: Test Action
on:
  push:
    branches: [feature/github_action_changes]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run My Action
        user:
          ./test-action.yml
