name: Test Action
on:
  issue_comment:
    types: [created]
    branches:
      - feature/github_action_changes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run My Action
        run: echo "Test Success!"
