name: Test Action
on:
  issue_comment:
    branches:
     - 'feature/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run My Action
        run: echo "Test Success!"
